# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  APPS_DIR: ../../apps/react-native-src
  CORE_DIR: ../../core/react-native

tasks:
  web:
    dir: "{{.CORE_DIR}}"
    cmd: bun expo start --web

  add:android:
    dir: "{{.CORE_DIR}}"
    cmd: bun expo prebuild --platform android

  android:
    dir: "{{.CORE_DIR}}"
    cmd: bun expo start --android

  android:build:
    dir: "{{.CORE_DIR}}"
    cmd: bun eas-cli build --platform android

  setup:
    cmds:
      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-native/node_modules/* {{.APPS_DIR}}/node_modules

      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-native/node_modules/.bin {{.APPS_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-native-src/node_modules/* {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-native-src/node_modules/.bin {{.CORE_DIR}}/node_modules
