# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  APPS_DIR: ../../apps/nest-src
  CORE_DIR: ../../core/nest

dotenv:
  - .env

env:
  NODE_ENV: development

tasks:
  cli:
    dir: "{{.APPS_DIR}}"
    cmd: bun nest {{.CLI_ARGS}}

  start:
    dotenv:
      - .env
    dir: "{{.APPS_DIR}}"
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest start

  build:
    dir: "{{.APPS_DIR}}"
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest build

  start:watch:
    dir: "{{.APPS_DIR}}"
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest start --watch

  start:watch:debug:
    dir: "{{.APPS_DIR}}"
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest start --watch --debug

  orm:init:
    dir: "{{.APPS_DIR}}"
    cmds:
      # - bun run prisma init --datasource-provider postgresql --output ./generated/prisma
      - bun prisma generate
      - bun prisma migrate dev --name init

  orm:deploy:
    dir: "{{.APPS_DIR}}"
    cmds:
      - task: orm:init
      - bun prisma migrate deploy
      - bun prisma db push

  setup:
    - cp -rf {{.APPS_DIR}}/node_modules/@deps/nest/node_modules/* {{.APPS_DIR}}/node_modules

    - cp -rf {{.APPS_DIR}}/node_modules/@deps/nest/node_modules/.bin {{.APPS_DIR}}/node_modules

    - cp -rf {{.APPS_DIR}}/node_modules/@deps/orm/node_modules/* {{.APPS_DIR}}/node_modules

    - cp -rf {{.APPS_DIR}}/node_modules/@deps/orm/node_modules/.bin {{.APPS_DIR}}/node_modules

    - cp -rf {{.CORE_DIR}}/node_modules/@deps/nest/node_modules/* {{.CORE_DIR}}/node_modules

    - cp -rf {{.CORE_DIR}}/node_modules/@deps/nest/node_modules/.bin {{.CORE_DIR}}/node_modules

    - cp -rf {{.CORE_DIR}}/node_modules/@deps/orm/node_modules/* {{.CORE_DIR}}/node_modules

    - cp -rf {{.CORE_DIR}}/node_modules/@deps/orm/node_modules/.bin {{.CORE_DIR}}/node_modules

    - cp -rf {{.CORE_DIR}}/node_modules/@apps/nest-src/node_modules/* {{.CORE_DIR}}/node_modules
    - cp -rf {{.CORE_DIR}}/node_modules/@apps/nest-src/node_modules/.bin {{.CORE_DIR}}/node_modules
