# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  compile:
    cmds:
      - bun tsc
      - bun build --compile --minify  --outfile=bin/ts-template lib/ts-template.ts

  biome:check:
    cmd: bun biome check

  biome:fix:
    cmd: bun biome check --fix

  biome:fix:unsafe:
    cmd: bun biome check --fix --unsafe

  biome:migrate:
    cmd: bun biome migrate --write

  test:
    cmd: bun vitest {{.CLI_ARGS}}

  cleanup:
    cmds:
      - rm -r node_modules
      - rm -r bin
