# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  init:
    cmds:
      - bun --cwd ../../core/react-vite biome init
      - bun --cwd ../../core/react-ionic-vite biome init
      - bun --cwd ../../core/react-electron-vite biome init
      - bun --cwd ../../core/react-native biome init
      - bun --cwd ../../core/nest biome init

      - bun --cwd ../../apps/react-vite-src biome init
      - bun --cwd ../../apps/react-ionic-vite-src biome init
      - bun --cwd ../../apps/react-electron-vite-src biome init
      - bun --cwd ../../apps/react-native-src biome init
      - bun --cwd ../../apps/nest-src biome init
    status:
      - test -f ../../core/react-vite/biome.json
      - test -f ../../core/react-ionic-vite/biome.json
      - test -f ../../core/react-electron-vite/biome.json
      - test -f ../../core/react-native/biome.json
      - test -f ../../core/nest/biome.json

      - test -f ../../apps/react-vite-src/biome.json
      - test -f ../../apps/react-ionic-vite-src/biome.json
      - test -f ../../apps/react-electron-vite-src/biome.json
      - test -f ../../apps/react-native-src/biome.json
      - test -f ../../apps/nest-src/biome.json

  check:
    cmds:
      - bun --cwd ../../core/react-vite  biome check
      - bun --cwd ../../core/react-ionic-vite  biome check
      - bun --cwd ../../core/react-electron-vite biome check
      - bun --cwd ../../core/react-native biome check
      - bun --cwd ../../core/nest biome check

      - bun --cwd ../../apps/react-vite-src biome check
      - bun --cwd ../../apps/react-ionic-vite-src biome check
      - bun --cwd ../../apps/react-electron-vite-src biome check
      - bun --cwd ../../apps/react-native-src biome check
      - bun --cwd ../../apps/nest-src biome check

  fix:
    cmds:
      - bun --cwd ../../core/react-vite biome check --fix
      - bun --cwd ../../core/react-ionic-vite biome check --fix
      - bun --cwd ../../core/react-electron-vite biome check --fix
      - bun --cwd ../../core/react-native biome check --fix
      - bun --cwd ../../core/nest biome check --fix

      - bun --cwd ../../apps/react-vite-src biome check --fix
      - bun --cwd ../../apps/react-ionic-vite-src biome check --fix
      - bun --cwd ../../apps/react-electron-vite-src biome check --fix
      - bun --cwd ../../apps/react-native-src biome check --fix
      - bun --cwd ../../apps/nest-src biome check --fix

  fix:unsafe:
    cmds:
      - bun --cwd ../../core/react-vite biome check --fix --unsafe
      - bun --cwd ../../core/react-ionic-vite biome check --fix --unsafe
      - bun --cwd ../../core/react-electron-vite biome check --fix --unsafe
      - bun --cwd ../../core/react-native biome check --fix --unsafe
      - bun --cwd ../../core/nest biome check --fix --unsafe

      - bun --cwd ../../apps/react-vite-src biome check --fix --unsafe
      - bun --cwd ../../apps/react-ionic-vite-src biome check --fix --unsafe
      - bun --cwd ../../apps/react-electron-vite-src biome check --fix --unsafe
      - bun --cwd ../../apps/react-native-src biome check --fix --unsafe
      - bun --cwd ../../apps/nest-src biome check --fix --unsafe

  migrate:
    cmds:
      - bun --cwd ../../core/react-vite biome migrate --write
      - bun --cwd ../../core/react-ionic-vite biome migrate --write
      - bun --cwd ../../core/react-electron-vite biome migrate --write
      - bun --cwd ../../core/react-native biome migrate --write
      - bun --cwd ../../core/nest biome migrate --write

      - bun --cwd ../../apps/react-vite-src biome migrate --write
      - bun --cwd ../../apps/react-ionic-vite-src biome migrate --write
      - bun --cwd ../../apps/react-electron-vite-src biome migrate --write
      - bun --cwd ../../apps/react-native-src biome migrate --write
      - bun --cwd ../../apps/nest-src biome migrate --write
