# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  APPS_DIR: ../../apps/react-electron-vite-src
  CORE_DIR: ../../core/react-electron-vite

tasks:
  dev:
    dir: "{{.CORE_DIR}}"
    cmd: bun electron-vite dev -- --no-sandbox

  build:
    dir: "{{.CORE_DIR}}"
    cmds:
      - tsc --composite false
      - bun electron-vite build

  postinstall:
    dir: "{{.CORE_DIR}}"
    cmd: bun electron-builder install-app-deps

  build:unpack:
    dir: "{{.CORE_DIR}}"
    cmds:
      - task: build
      - cmd: bun electron-builder --dir

  build:linux:
    dir: "{{.CORE_DIR}}"
    cmds:
      - task: build
      - cmd: bun electron-builder --linux

  build:win:
    dir: "{{.CORE_DIR}}"
    cmds:
      - task: build
      - cmd: bun electron-builder --win

  build:mac:
    dir: "{{.CORE_DIR}}"
    cmds:
      - task: build
      - cmd: bun electron-builder --mac
  setup:
    cmds:
      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-electron-vite/node_modules/* {{.APPS_DIR}}/node_modules

      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-electron-vite/node_modules/.bin {{.APPS_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-electron-vite-src/node_modules/* {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-electron-vite-src/node_modules/.bin {{.CORE_DIR}}/node_modules
