# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  APPS_DIR: ../../apps/react-ionic-vite-src
  CORE_DIR: ../../core/react-ionic-vite

tasks:
  web:
    dir: "{{.CORE_DIR}}"
    cmd: bun run vite

  web:build:
    dir: "{{.CORE_DIR}}"
    cmds:
      - tsc -b
      - bun run vite build
    status:
      - test -d dist

  web:test:browser:
    dir: "{{.CORE_DIR}}"
    cmd: bun vitest {{.CLI_ARGS}}

  add:android:
    dir: "{{.CORE_DIR}}"
    cmd: bun cap add android
    status:
      - test -d android

  android:
    dir: "{{.CORE_DIR}}"
    cmds:
      - task: web:build
      - defer: bun cap run android
      - task: add:android

  setup:
    cmds:
      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-ionic-vite/node_modules/* {{.APPS_DIR}}/node_modules

      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-ionic-vite/node_modules/.bin {{.APPS_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@deps/react-ionic-vite/node_modules/* {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@deps/react-ionic-vite/node_modules/.bin {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-ionic-vite-src/node_modules/* {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-ionic-vite-src/node_modules/.bin {{.CORE_DIR}}/node_modules
