# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  web:
    dir: ../../core/react-ionic-vite
    cmd: bun run vite

  web:build:
    dir: ../../core/react-ionic-vite
    cmds:
      - tsc -b
      - bun run vite build

  web:test:browser:
    dir: ../../tests/react-ionic-vite
    cmd: bun vitest

  add:android:
    dir: ../../core/react-ionic-vite
    prompt: "Are you sure you want to add android?"
    cmd: bun cap add android

  android:
    cmds:
      - task: web:build
      - defer: bun --cwd ../../core/react-ionic-vite cap run android
      - task: add:android

  setup:
    - cp -rf ../../apps/react-ionic-vite-src/node_modules/@deps/react-ionic-vite/node_modules/* ../../apps/react-ionic-vite-src/node_modules
    - cp -rf ../../apps/react-ionic-vite-src/node_modules/@deps/react-ionic-vite/node_modules/.bin ../../apps/react-ionic-vite-src/node_modules

    - cp -rf ../../core/react-ionic-vite/node_modules/@deps/react-ionic-vite/node_modules/* ../../core/react-ionic-vite/node_modules
    - cp -rf ../../core/react-ionic-vite/node_modules/@deps/react-ionic-vite/node_modules/.bin ../../core/react-ionic-vite/node_modules

    - cp -rf ../../core/react-ionic-vite/node_modules/@apps/react-ionic-vite-src/node_modules/* ../../core/react-ionic-vite/node_modules
    - cp -rf ../../core/react-ionic-vite/node_modules/@apps/react-ionic-vite-src/node_modules/.bin ../../core/react-ionic-vite/node_modules

    - defer: cp -rf ../../apps/react-ionic-vite-src/node_modules/@packages/react-ionic-vite/node_modules/* ../../apps/react-ionic-vite-src/node_modules

    - cp -rf ../../tests/react-ionic-vite/node_modules/@deps/react-ionic-vite/node_modules/*
      ../../tests/react-ionic-vite/node_modules

    - cp -rf ../../tests/react-ionic-vite/node_modules/@deps/react-ionic-vite/node_modules/.bin ../../tests/react-ionic-vite/node_modules
