# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  build:
    cmd: cmake -GNinja . -B build {{.CLI_ARGS}}

  build:compile:
    cmds:
      - task: build
      - task: compile

  compile:
    cmds:
      - ninja -C build
      - sudo cp -rvf ./bin/ghost-convert /usr/local/bin/ghost-convert

  compile:run:
    cmds:
      - task: compile
      - ghost-convert {{.CLI_ARGS}}

  test:
    cmds:
      - task: compile
      - ./bin/ghost-convert-test {{.CLI_ARGS}}

  test:watch:
    cmd: watchexec -r -c -e cpp,hpp,txt,cmake -- task test

  cleanup:
    cmds:
      - rm -r build
      - rm -r bin
