# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  APPS_DIR: ../../apps/react-vite-src
  CORE_DIR: ../../core/react-vite

tasks:
  web:
    dir: "{{.CORE_DIR}}"
    cmd: bun vite

  web:build:
    dir: "{{.CORE_DIR}}"
    cmds:
      - tsc -b
      - bun vite build

  web:test:browser:
    dir: "{{.CORE_DIR}}"
    cmd: bun vitest {{.CLI_ARGS}}

  setup:
    cmds:
      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-vite/node_modules/* {{.APPS_DIR}}/node_modules

      - cp -rf {{.APPS_DIR}}/node_modules/@deps/react-vite/node_modules/.bin {{.APPS_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@deps/react-vite/node_modules/* {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@deps/react-vite/node_modules/.bin {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-vite-src/node_modules/* {{.CORE_DIR}}/node_modules

      - cp -rf {{.CORE_DIR}}/node_modules/@apps/react-vite-src/node_modules/.bin {{.CORE_DIR}}/node_modules
