# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  web:
    dir: ../../core/react-vite
    cmd: bun vite

  web:build:
    dir: ../../core/react-vite
    cmds:
      - tsc -b
      - bun vite build

  web:test:browser:
    dir: ../../tests/react-vite
    cmd: bun vitest

  setup:
    - cp -rf ../../apps/react-vite-src/node_modules/@deps/react-vite/node_modules/* ../../apps/react-vite-src/node_modules

    - cp -rf ../../apps/react-vite-src/node_modules/@deps/react-vite/node_modules/.bin ../../apps/react-vite-src/node_modules

    - cp -rf ../../core/react-vite/node_modules/@deps/react-vite/node_modules/* ../../core/react-vite/node_modules

    - cp -rf ../../core/react-vite/node_modules/@deps/react-vite/node_modules/.bin ../../core/react-vite/node_modules

    - cp -rf ../../core/react-vite/node_modules/@apps/react-vite-src/node_modules/* ../../core/react-vite/node_modules

    - cp -rf ../../core/react-vite/node_modules/@apps/react-vite-src/node_modules/.bin ../../core/react-vite/node_modules

    - defer: cp -rf ../../apps/react-vite-src/node_modules/@packages/react-vite/node_modules/* ../../apps/react-vite-src/node_modules

    - cp -rf ../../tests/react-vite/node_modules/@deps/react-vite/node_modules/*
      ../../tests/react-vite/node_modules

    - cp -rf ../../tests/react-vite/node_modules/@deps/react-vite/node_modules/.bin ../../tests/react-vite/node_modules
